# Generated by Django 3.0.5 on 2022-10-07 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ci', models.CharField(max_length=100)),
                ('names', models.CharField(max_length=100)),
                ('firts_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('birthay_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Person')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='PartAssistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Authority')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Responsible')),
            ],
        ),
        migrations.AddField(
            model_name='authority',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Person'),
        ),
        migrations.AddField(
            model_name='authority',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.Unit'),
        ),
    ]
