# Generated by Django 3.0.5 on 2022-10-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
